CREATE DATABASE shopping_db;
USE shopping_db;
CREATE TABLE customer_shopping_behavior (
    customer_id INT,
    age INT,
    gender VARCHAR(10),
    item_purchased VARCHAR(50),
    category VARCHAR(50),
    purchase_amount DECIMAL(10,2),
    location VARCHAR(50),
    size VARCHAR(10),
    color VARCHAR(20),
    season VARCHAR(20),
    review_rating DECIMAL(3,1),
    subscription_status VARCHAR(5),
    shipping_type VARCHAR(30),
    discount_applied VARCHAR(5),
    promo_code_used VARCHAR(5),
    previous_purchases INT,
    payment_method VARCHAR(30),
    frequency_of_purchases VARCHAR(30)
    );
SELECT * FROM customer_shopping_behavior LIMIT 10;

SELECT COUNT(*) FROM customer_shopping_behavior;
SELECT DISTINCT category FROM customer_shopping_behavior;
SELECT DISTINCT payment_method FROM customer_shopping_behavior;

#Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer_shopping_behavior 
group by gender;

#Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount
FROM customer_shopping_behavior
WHERE discount_applied = 'Yes'
AND purchase_amount > (
    SELECT AVG(purchase_amount) 
    FROM customer_shopping_behavior
);

#Q3. Top 5 products with highest average review rating
SELECT item_purchased, 
       ROUND(AVG(review_rating),2) AS avg_product_rating
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY avg_product_rating DESC
LIMIT 5;

#Avg Purchase Amount: Standard vs Express Shipping
SELECT shipping_type, 
       ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer_shopping_behavior
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

#Q5. Subscribed vs Non-Subscribed Customers Analysis
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_shopping_behavior
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

#Q6. Top 5 products with highest discount usage %
SELECT item_purchased,
       ROUND(100 * SUM(CASE 
              WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
              / COUNT(*), 2) AS discount_rate
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

#7. Customer Segmentation (New / Returning / Loyal)


SELECT customer_segment, COUNT(*) AS number_of_customers
FROM (
    SELECT customer_id,
           CASE 
              WHEN previous_purchases = 1 THEN 'New'
              WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
              ELSE 'Loyal'
           END AS customer_segment
    FROM customer_shopping_behavior
) t
GROUP BY customer_segment;

#Q8. Top 3 Products in Each Category
SELECT category, item_purchased, total_orders
FROM (
    SELECT category,
           item_purchased,
           COUNT(*) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rn
    FROM customer_shopping_behavior
    GROUP BY category, item_purchased
) ranked
WHERE rn <= 3;

#Q9. Repeat Buyers (>5 purchases) vs Subscription
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_shopping_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;

#Q10. Revenue by Age Group
SELECT 
   CASE 
      WHEN age < 25 THEN 'Under 25'
      WHEN age BETWEEN 25 AND 34 THEN '25-34'
      WHEN age BETWEEN 35 AND 44 THEN '35-44'
      WHEN age BETWEEN 45 AND 54 THEN '45-54'
      ELSE '55+'
   END AS age_group,
   SUM(purchase_amount) AS total_revenue
FROM customer_shopping_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;
